# Generated by Django 5.1.4 on 2024-12-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
